In [1]:
import torch as t
import torch.nn as nn
import pandas as pd
import numpy as np
from tqdm import tqdm
from sae_lens import (
    SAE,
    ActivationsStore,
    HookedSAETransformer,
    LanguageModelSAERunnerConfig,
    SAEConfig,
    SAETrainingRunner,
    upload_saes_to_huggingface,
)

In [2]:
?t.optim.AdamW

Init signature:
t.optim.AdamW(
    params: Union[Iterable[torch.Tensor], Iterable[Dict[str, Any]], Iterable[Tuple[str, torch.Tensor]]],
    lr: Union[float, torch.Tensor] = 0.001,
    betas: Tuple[Union[float, torch.Tensor], Union[float, torch.Tensor]] = (0.9, 0.999),
    eps: float = 1e-08,
    weight_decay: float = 0.01,
    amsgrad: bool = False,
    *,
    maximize: bool = False,
    foreach: Optional[bool] = None,
    capturable: bool = False,
    differentiable: bool = False,
    fused: Optional[bool] = None,
)
Docstring:     
Implements AdamW algorithm.

.. math::
   \begin{aligned}
        &\rule{110mm}{0.4pt}                                                                 \\
        &\textbf{input}      : \gamma \text{(lr)}, \: \beta_1, \beta_2
            \text{(betas)}, \: \theta_0 \text{(params)}, \: f(\theta) \text{(objective)},
            \: \epsilon \text{ (epsilon)}                                                    \\
        &\hspace{13mm}      \lambda \text{(weight 

In [2]:
model2b = HookedSAETransformer.from_pretrained("gemma-2-2b", device = 'cuda')

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Loaded pretrained model gemma-2-2b into HookedTransformer


In [4]:
city_alice = pd.read_csv("cities_alice.csv")
neg_city_alice = pd.read_csv("neg_cities_alice.csv")
data = pd.concat([city_alice, neg_city_alice])
#scramble rows
np.random.seed(123)
data = data.sample(frac = 1).reset_index(drop = True)
data.head(10)

statement  label              city  \
0           Alice: The city of Hegang is in China.      1            Hegang   
1           Bob: The city of Cangzhou is in China.      1          Cangzhou   
2      Alice: The city of Mogadishu is in Somalia.      1         Mogadishu   
3          Bob: The city of Laibin is in Ethiopia.      0            Laibin   
4  Bob: The city of Feira de Santana is in Brazil.      1  Feira de Santana   
5   Alice: The city of Karachi is not in Pakistan.      0           Karachi   
6           Alice: The city of Luohe is in Brazil.      0             Luohe   
7       Bob: The city of Tlalpan is not in Mexico.      0           Tlalpan   
8             Bob: The city of Bekasi is in China.      0            Bekasi   
9     Alice: The city of Langfang is not in India.      1          Langfang   

    country correct_country  has_alice  has_not  has_alice xor has_not  \
0     China           China       True    False                   True   
1     China           China      False    False                  False   
2   Somalia         Somalia       True    False                   True   
3  Ethiopia           China      False    False                  False   
4    Brazil          Brazil      False    False                  False   
5  Pakistan        Pakistan       True     True                  False   
6    Brazil           China       True    False                   True   
7    Mexico          Mexico      False     True                   True   
8     China       Indonesia      False    False                  False   
9     India           China       True     True                  False   

   has_alice xor label  has_not xor label  has_alice xor has_not xor label  
0                False               True                            False  
1                 True               True                             True  
2                False               True                            False  
3                False              False                            False  
4                 True               True                             True  
5                 True               True                            False  
6                 True              False                             True  
7                False               True                             True  
8                False              False                            False  
9                False              False                             True

In [12]:
data.shape

(2992, 11)

In [4]:
model2b.cfg

HookedTransformerConfig:
{'NTK_by_parts_factor': 8.0,
 'NTK_by_parts_high_freq_factor': 4.0,
 'NTK_by_parts_low_freq_factor': 1.0,
 'act_fn': 'gelu_pytorch_tanh',
 'attention_dir': 'causal',
 'attn_only': False,
 'attn_scale': 16.0,
 'attn_scores_soft_cap': 50.0,
 'attn_types': ['global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'globa

In [3]:
sae, cfg_dict, sparsity = SAE.from_pretrained(
    release = "gemma-scope-2b-pt-res-canonical",
    sae_id = "layer_19/width_16k/canonical",
    device = "cuda"
)

In [6]:
a = model2b.generate("Bing bong ding dong", max_new_tokens = 10)
a

  0%|          | 0/10 [00:00<?, ?it/s]

"Bing bong ding dong, I'm blowing this one, 9"

In [5]:
some_batch = model2b.tokenizer(["Ding don bing bong", "King kong ding dong whoop whoop"], return_tensors = "pt", padding = True).to("cuda")

In [6]:
some_batch['attention_mask']

tensor([[1, 1, 1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0')

In [7]:
leb = model2b.run_with_cache_with_saes(some_batch['input_ids'],saes = sae)

In [8]:
leb[1].keys()

dict_keys(['hook_embed', 'blocks.0.hook_resid_pre', 'blocks.0.ln1.hook_scale', 'blocks.0.ln1.hook_normalized', 'blocks.0.attn.hook_q', 'blocks.0.attn.hook_k', 'blocks.0.attn.hook_v', 'blocks.0.attn.hook_rot_q', 'blocks.0.attn.hook_rot_k', 'blocks.0.attn.hook_attn_scores', 'blocks.0.attn.hook_pattern', 'blocks.0.attn.hook_z', 'blocks.0.ln1_post.hook_scale', 'blocks.0.ln1_post.hook_normalized', 'blocks.0.hook_attn_out', 'blocks.0.hook_resid_mid', 'blocks.0.ln2.hook_scale', 'blocks.0.ln2.hook_normalized', 'blocks.0.mlp.hook_pre', 'blocks.0.mlp.hook_pre_linear', 'blocks.0.mlp.hook_post', 'blocks.0.ln2_post.hook_scale', 'blocks.0.ln2_post.hook_normalized', 'blocks.0.hook_mlp_out', 'blocks.0.hook_resid_post', 'blocks.1.hook_resid_pre', 'blocks.1.ln1.hook_scale', 'blocks.1.ln1.hook_normalized', 'blocks.1.attn.hook_q', 'blocks.1.attn.hook_k', 'blocks.1.attn.hook_v', 'blocks.1.attn.hook_rot_q', 'blocks.1.attn.hook_rot_k', 'blocks.1.attn.hook_attn_scores', 'blocks.1.attn.hook_pattern', 'blocks.1

In [9]:
leb[1]['blocks.19.hook_resid_post.hook_sae_acts_pre']

tensor([[[ 5.2232e+01, -2.7003e+01,  4.6542e+00,  ..., -5.2398e+01,
           2.0997e+01,  2.1721e-01],
         [-6.7635e+00, -6.1891e+00, -1.1391e+01,  ..., -8.5298e+00,
          -1.1453e+00, -1.9739e+00],
         [-1.6946e+01, -4.8029e+00, -1.9131e+00,  ..., -4.0972e+00,
           3.4327e+00, -5.6123e+00],
         ...,
         [-6.1531e+00, -4.0606e+00, -7.6024e+00,  ..., -2.5864e+00,
          -3.1558e+00, -3.7671e+00],
         [-6.5121e+00, -3.5599e+00, -7.1476e+00,  ..., -2.5776e+00,
          -3.4720e+00, -3.5249e+00],
         [-5.8592e+00, -3.5852e+00, -6.8130e+00,  ..., -3.1476e+00,
          -3.7623e+00, -3.7608e+00]],

        [[ 5.2232e+01, -2.7003e+01,  4.6542e+00,  ..., -5.2398e+01,
           2.0997e+01,  2.1721e-01],
         [-1.6245e+01,  2.8613e+00, -7.4969e+00,  ..., -6.8718e+00,
          -1.0947e+01, -6.6743e+00],
         [-1.6009e+01, -1.0201e+00, -9.5743e+00,  ..., -8.3371e+00,
          -5.1224e+00, -3.5708e+00],
         ...,
         [-2.8493e+01, -7

In [31]:
hmm = leb[1]['blocks.19.hook_resid_post.hook_sae_acts_post'][:,1,:]


In [32]:
for h in hmm:
    print(h)

tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')


In [28]:
leb[1]['blocks.19.hook_resid_post.hook_sae_acts_post'][    1,     0,     263]

tensor(31.0618, device='cuda:0')

In [26]:
t.nonzero(leb[1]['blocks.19.hook_resid_post.hook_sae_acts_post'][:,1:,:])

tensor([[    0,     0,     4],
        [    0,     0,   263],
        [    0,     0,   774],
        ...,
        [    1,     7, 16209],
        [    1,     7, 16303],
        [    1,     7, 16372]], device='cuda:0')

In [12]:
indices = (leb[1]['blocks.19.hook_resid_post.hook_sae_acts_post'] > 0).nonzero(as_tuple=True)[0]


tensor([[[ True, False, False,  ..., False,  True, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[ True, False, False,  ..., False,  True, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]]], device='cuda:0')

In [ ]:
batch_out = model.run_with_cache_with_saes(
            batch_ids,
            saes=sae,
            names_filter=lambda name: name in [
                'blocks.19.hook_resid_post.hook_sae_input',
                'blocks.19.hook_resid_post.hook_sae_recons'
            ]
        )[1]

In [44]:
leb[1]['blocks.19.hook_resid_post.hook_sae_recons']
# tensor([[[ 6.3655e+01,  2.7575e+02, -1.7398e+02,  ...,  2.9820e+02,
        #   -6.2675e+01,  2.9702e+01],
        #  [-4.8884e+00, -6.8970e-01,  4.2473e-01,  ...,  2.6384e+00,
        #    7.4499e-01,  1.6682e-01],
        #  [-3.9028e+00, -8.6650e-01, -4.0607e+00,  ...,  1.5525e+00,
        #    5.1970e+00, -1.1291e-01],
        #  [-5.4336e+00,  1.4239e+00,  2.3322e+00,  ...,  1.5917e+00,
        #   -5.3451e-01,  2.7083e+00],
        #  [-9.6548e+00,  3.2607e+00,  4.4400e+00,  ..., -2.2930e+00,
        #    1.9895e+00,  2.9883e+00]],

tensor([[[ 6.3655e+01,  2.7575e+02, -1.7398e+02,  ...,  2.9820e+02,
          -6.2675e+01,  2.9702e+01],
         [-4.8884e+00, -6.8970e-01,  4.2473e-01,  ...,  2.6384e+00,
           7.4499e-01,  1.6682e-01],
         [-3.9028e+00, -8.6650e-01, -4.0607e+00,  ...,  1.5525e+00,
           5.1970e+00, -1.1291e-01],
         [-5.4336e+00,  1.4239e+00,  2.3322e+00,  ...,  1.5917e+00,
          -5.3451e-01,  2.7083e+00],
         [-9.6548e+00,  3.2607e+00,  4.4400e+00,  ..., -2.2930e+00,
           1.9895e+00,  2.9883e+00]],

        [[ 6.3655e+01,  2.7575e+02, -1.7398e+02,  ...,  2.9820e+02,
          -6.2675e+01,  2.9702e+01],
         [-6.8911e+00,  8.6366e+00, -2.9912e+00,  ...,  7.0088e-01,
          -1.5728e+00,  1.3779e+00],
         [-4.2630e+00,  1.3513e+00, -2.4401e+00,  ..., -2.6403e+00,
          -4.0709e+00,  3.4806e+00],
         [-3.7446e+00, -6.9691e-01, -8.2747e-01,  ...,  5.4570e+00,
          -1.1321e+00,  3.9979e-01],
         [-6.1591e+00,  2.7186e+00, -5.2874e-01,  ...

In [ ]:
class Probe(nn.Module):
    def __init__(self, activation_dim):
        super().__init__()
        self.net = nn.Linear(activation_dim, 1, bias=True)

    def forward(self, x):
        logits = self.net(x).squeeze(-1)
        return logits

def train_probe(get_acts, label_idx=0, batches=get_data(), lr=1e-2, epochs=1, dim=512, seed=SEED):
    t.manual_seed(seed)
    probe = Probe(dim).to('cuda')
    optimizer = t.optim.AdamW(probe.parameters(), lr=lr)
    criterion = nn.BCEWithLogitsLoss()

    losses = []
    for epoch in range(epochs):
        for batch in tqdm(batches):
            text = batch[0]
            labels = batch[label_idx+1]
            acts = get_acts(text)
            logits = probe(acts)
            loss = criterion(logits, labels.float())
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            losses.append(loss.item())

    return probe, losses

In [ ]:
#Other people's code

labels = [
    'has_alice',
    'has_not',
    'label',
    'has_alice xor has_not',
    'has_alice xor label',
    'has_not xor label',
    'has_alice xor has_not xor label',
]
    
accs = {}
for label in labels:
    dm = DataManager()
    for dataset in ['cities_alice', 'neg_cities_alice']:
        dm.add_dataset(dataset, 'llama-2-13b-reset', 14, label=label, center=False, split=0.8)
    acts, labels = dm.get('train')
    probe = LRProbe.from_data(acts, labels, bias=True)
    acts, labels = dm.get('val')
    acc = (probe(acts).round() == labels).float().mean()
    accs[label] = acc